name: Example documentation with Unity action

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library

      - uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          buildMethod: UnityEditor.SyncVS.SyncSolution
          targetPlatform: StandaloneLinux64

      - name: Display unity install
        run: ls -R /opt/unity/Editor/Data/Tools/RoslynScripts

      - name: Upload csproj artifact
        uses: actions/upload-artifact@v2
        with:
          name: csproj
          path: ./**/*.csproj

      - name: Use README.md as index.md
        run: cp README.md Documentation/index.md

      - name: Build
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: Documentation/docfx.json

      - name: Display site files
        run: ls -R _site

      - name: Upload site artifact
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site