name: Example documentation with Unity action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library

      - uses: game-ci/unity-builder@2.0-alpha-6
        with:
          buildMethod: UnityEditor.SyncVS.SyncSolution
          targetPlatform: StandaloneLinux64

      - name: Display csproj files
        run: ls *.csproj

      - name: Upload csproj artifact
        uses: actions/upload-artifact@v2
        with:
          name: csproj
          path: ./*.csproj

      #- name: Setup DocFX
      #  run: |
      #    wget https://github.com/dotnet/docfx/releases/download/v2.56.6/docfx.zip
      #    unzip docfx -d docfx

      - name: Use README.md as index.md
        run: cp README.md Documentation/index.md

      - name: Build
        uses: tsgkadot/docker-docfx:latest
        with:
          args: docfx Documentation/docfx.json

      - name: Display site files
        run: ls -R _site

      - name: Upload site artifact
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site